scp elderberry.in.caiyunapp.com:~/star-sensor/0.png .
scp elderberry.in.caiyunapp.com:~/star-sensor/1.png .
scp elderberry.in.caiyunapp.com:~/star-sensor/2.png .
scp elderberry.in.caiyunapp.com:~/star-sensor/3.png .
scp elderberry.in.caiyunapp.com:~/star-sensor/4.png .
scp elderberry.in.caiyunapp.com:~/star-sensor/5.png .
scp elderberry.in.caiyunapp.com:~/star-sensor/6.png .
scp elderberry.in.caiyunapp.com:~/star-sensor/7.png .
scp elderberry.in.caiyunapp.com:~/star-sensor/8.png .
scp elderberry.in.caiyunapp.com:~/star-sensor/9.png .
